"use client";

import { useState, useEffect } from 'react';
import { initConversation } from "@/services/carqnaService"; 
import { CopilotKit } from "@copilotkit/react-core";
import "@copilotkit/react-ui/styles.css";
import { ChatInterface } from "@/components/ChatInterface";

export default function Home() {
  const [activeThreadId, setActiveThreadId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function setupSession() {
      try {
        // 1. Fire your working custom fetch initialization endpoint
        const response = await initConversation("user-123");
        
        // 2. Capture the exact thread ID generated by your python backend
        if (response.thread_id) {
          setActiveThreadId(response.thread_id);
        }
      } catch (err) {
        console.error("Failed to initialize active workspace context session:", err);
      } finally {
        setLoading(false);
      }
    }
    setupSession();
  }, []);

  if (loading) return <div>Initializing secure workspace...</div>;

  return (
    <CopilotKit 
      runtimeUrl={process.env.NEXT_PUBLIC_API_BASE}
      publicApiKey=""
      // Explicitly pin the chat widget to the session your backend initialized
      threadId={activeThreadId || undefined} 
    >
      <ChatInterface />
    </CopilotKit>
  );
}
